### ISSUE TITLE
Splitting issue

### ISSUE THREAD

**Issue by StanislavGafarov** [deepmipt/ru_sentence_tokenizer#3]
Пример предложений: "Картина «Московская улица XVII века в праздничный день» была представлена на 1-й выставке Общества художников исторической живописи (ОХИЖ), открывшейся в Москве в марте 1895 года.В 1900 году три полотна Рябушкина, включая «Московскую улицу», были частью российской экспозиции на Всемирной выставке в Париже; за них художник был отмечен почётным отзывом выставки и получил почётный диплом."
к сожалению на выходе получаем список длинны 1.

**Comment by tsundokum** [comment]
К сожалению одна из эвристик не разделять предложение -- это отсутствие пробела после точки. Если у вас много таких предложений, но хочется использовать этот токенайзер (остальные эвристики подходят), то можно попробовать сначала самому проставлять пробелы перед точкой. Но если это не ip-адрес, не вебсайт, не число, и тп, что нужно внимательно просматривать. 

Сейчас убрать эту эвристику не представляется простой задачей, так как тогда сломаются остальные правила.
